### ISSUE TITLE
ambigious terminology

### ISSUE THREAD

**Issue by azhang** [Privatix/dappctrl#438]
https://github.com/Privatix/dappctrl/blob/d3efe9b08749c6c7635ec9c9ca826e7a07e2cfb7/agent/somcsrv/client.go#L42

Confusing because "method" when used in context of making an http request usually refers to http methods (GET, POST, PUT, etc) rather than a function name

**Comment by furkhat** [comment]
Hey, thanks for the feedback. You should think in context of this particular "use case" too.
https://github.com/Privatix/dappctrl/blob/d3efe9b08749c6c7635ec9c9ca826e7a07e2cfb7/agent/somcsrv/client.go#L52
